- hosts: master
  become: yes
  tasks:
    - name: Initalize the Cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
         chdir: $HOME
         creates: cluster_initialized.txt

    - name: Create .kube directory
      become: yes
      become_user: master-node
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/master-node/.kube/config
        remote_src: yes
        owner: master-node

    - name: Install Pod Network
      become: yes
      become_user: master-node
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
